#ParallelParking_Scenario_ReedShepp
#ParallelParking_Scenario_Dubin
#Parking_Scenario_ReedsShepp
#Parking_Scenario_Dubin
#Street_Scenario_ReedsShepp
#Street_Scenario_Dubin

from bin.run_controller import run_sim
from Parking_Scenario_ReedsShepp import TestScenario
from csv_utils import csv_keys

run_sim(TestScenario, csv_keys["Parking_Scenario_ReedsShepp"])